spring.application.name=backend
server.port=${PORT:8090}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/diazburguer}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

app.frontend-url=${FRONTEND_URL:http://localhost:5173}

server.servlet.session.cookie.same-site=${COOKIE_SAME_SITE:Lax}
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
